services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001
      - PORT=3000
      - SKIP_PREFLIGHT_CHECK=true
